### ISSUE TITLE
remove dependency on addons-vauxoo

### ISSUE THREAD

**Issue by gurneyalex** [OCA/account-invoicing#10]
There are addons in there with dependencies on addons-vauxoo (cf. travis configuration). 

Either the dependency must be ported to OCA, or thes addons must be removed from the repository.

**Comment by nhomar** [comment]
Hello Friend.
Which addons depends of addons-vauxoo ones?

**Comment by pedrobaeza** [comment]
Hi, Nhomar,

Module _product_customer_code_invoice_ depends on _product_customer_code_, which is in your repository, but I think there isn't any other dependency.

Regards.

**Comment by nhomar** [comment]
Ok Got it.

These both modules were migrated to OCA:

https://github.com/OCA/product-attribute/tree/7.0/product_customer_code

That's the product_customer_code in OCA already.

Regards.

**Comment by pedrobaeza** [comment]
Please remove it from your repository then to avoid that apps.openerp.com points to it.

**Comment by nhomar** [comment]
I will edit the website of the module, 

I can't just remove it from my branch because I can brake my internal installation/update processes in my customers.

What do you propose dude?

**Comment by pedrobaeza** [comment]
For the moment, please review PR that changes dependency.

About your installations, can you add product-attribute branch in them?

**Comment by nhomar** [comment]
Ok I am waiting for travis.

about my installations:

Yes, That's a WiP we are migrating all our platform to github, not ready yet, we were 100% on Launchpad and weverything over it :-(. Let's left open this issue until I solve that there.....
