### ISSUE TITLE
[13cm] account_global_discount journal item on journal entry without partner

### ISSUE THREAD

**Issue by sergioeix** [OCA/account-invoicing#1093]
## Module
account_global_discount
## Describe the bug
When the journal entries with global discount on the configured accounts are created this journal items dont have a partner

## To Reproduce
**Affected versions**:13 and other versions
1. Make an invoice with global discount
2. Check the journal items of the journal entry (incoice)
3. The accounts configured for global discounts dont have a the partner

**Expected behavior**
This journal items should have the partner set on the journal entry (invoice)

**Additional context**
Ubuntu 20.04

**Comment by pedrobaeza** [comment]
I have just tried, and it's putting the partner.

**Comment by sergioeix** [comment]
Lets close this, it was my fault.
