### ISSUE TITLE
[14.0] account_invoice_line_description: Tests are red in the pull requests

### ISSUE THREAD

**Issue by rolandojduartem** [OCA/account-invoicing#1157]
Hi @Tecnativa and @ernestotejeda, I noticed that the tests are red because of this module, you can see this here https://github.com/OCA/account-invoicing/pull/1104, we tried with the changes of that pull request and without them and the result persists. Please, may you fix it?

## Module
account_invoice_line_description

## Traceback

Traceback: https://gist.github.com/rolandojduartem/c54d8c5809aa557e155ff04f0ae84db6
Full test: https://github.com/OCA/account-invoicing/runs/6427624166?check_suite_focus=true

## To Reproduce
**Affected versions**: 14.0

cc @moylop260 @luisg123v

**Comment by matteoopenf** [comment]
@moylop260  or @luisg123v  can you fix it?

**Comment by pedrobaeza** [comment]
On the merge moment, it was green, so it should be a change in Odoo upstream.

**Comment by JuanyDForgeflow** [comment]
@rolandojduartem @matteoopenf I fixed it here https://github.com/OCA/account-invoicing/pull/1172

**Comment by tafaRU** [comment]
> @rolandojduartem @matteoopenf I fixed it here #1172

From which I extracted https://github.com/OCA/account-invoicing/pull/1175
