### ISSUE TITLE
Why to make a cash rounding if the payment is not in cash?

### ISSUE THREAD

**Issue by lapagept** [OCA/account-invoicing#118]
Hello guys,

As you know, in Sweden and in Canada, they do cash rounding (https://en.wikipedia.org/wiki/Cash_rounding). 

In those two countries cash rounding is applied only to purchase paid in CASH. Not to purchase paid with check or credit card.

So, I have installed the module account_invoice_rounding in my Odoo 8.0 (https://github.com/OCA/account-invoicing/tree/8.0/account_invoice_rounding).

This module make a new « rounding » line in an invoice when we update or save this invoice.

The problem :

When we create a new invoice, this invoice is not paid. It is open. Why does the module create a new line if it doesn't even know if the payment will be in cash????

If the payment is not made in cash, we don't have to make a cash rounding...

Do you agree? How do you see it?

**Comment by pedrobaeza** [comment]
This is out of the scope of the module, so an improvement should be done for covering that.
