### ISSUE TITLE
[10.0] stock_picking_invoicing: 'module' object has no attribute 'first'

### ISSUE THREAD

**Issue by serbata** [OCA/account-invoicing#1187]
## Module
stock_picking_invoicing

## Describe the bug
I cant do anything, because the import of field dont have first() function and that is breaking the code.

## To Reproduce
Install stock_picking_invoicing v.10.0 - and try the wizard Create Draft Invoices

**Additional context**
I only want to know if i need to install another module for the method first or its just a bad instalation

**Comment by AaronHForgeFlow** [comment]
Are you able to reproduce it in runboat?
