### ISSUE TITLE
Can't group by account if the entry is from pos

### ISSUE THREAD

**Issue by dimitrisand** [OCA/account-invoicing#120]
Can't group by account if the entry is from pos. If the entry is from Sales (different journal)everything is OK

**Comment by pedrobaeza** [comment]
Please document correctly the issue as when you click in the bug tracker section:
- module
- version
- Steps to reproduce
- Current behavior
- Expected behavior

**Comment by bodedra** [comment]
Due to lack of information, we can close these.
