### ISSUE TITLE
[ADD] partner_account_journal_default

### ISSUE THREAD

**Issue by rafaelbn** [OCA/account-invoicing#1291]
Hello,

We are going to develop a module in order to set  in partner a default purchase journal in a similar way than payment_term

Partner will have in accounting a Journal for sales and a Journal for purchase and in the moment you set the partner in the invoice the journal of the partner is set in the invoice. Standard behaviour is that the first journal (sequence) of the account move type is set.

- This would be use full when you have groups of suppliers which have a specified sequence or special requirements for the journals on that suppliers.
- In the same way this happens with customers for example if each customer has a single invoice sequence.

Needed in accounting without installing purchase or sales.

Regards,
Rafael

@moduon MT-906 @Shide

**Comment by legalsylvain** [comment]
I'm interessed by this feature. (For customer and supplier invoices)
Please ping me when the module is available.
Thanks !

**Comment by bodedra** [comment]
+1 account_journal_partner_default

**Comment by rafaelbn** [comment]
Hello @bodedra usually name of module beging with the main model they modify something, in this case res.partner so I think is better

`partner_account_journal_default`

Thank you! 😄
