### ISSUE TITLE
account_invoice_triple_discount report blocks Invoice print out

### ISSUE THREAD

**Issue by SkiBY** [OCA/account-invoicing#1375]
## Module
account_invoice_triple_discount

## Describe the bug
In account_invoice_triple_discount addon v.16 there is _has_dicsount method [used](https://github.com/OCA/account-invoicing/blob/3df9b963ff00ec96172af616f62bca3f08b8f2f3/account_invoice_triple_discount/report/invoice.xml#L5
).
There is no such a method in account.move class. 

## To Reproduce
**Affected versions**:
16.0

1. Install account_invoice_triple_discount
2. Go to Invoices and try to print out standard one of the two Reports

**Expected behavior**
Report is generated without errors

**Context**

All the account.move customization are removed when the module was ported to 16.
Probably @ramiadavid  can look through it as a port creator

**Comment by ramiadavid** [comment]
Hi @SkiBY fixed in #1378
