### ISSUE TITLE
Copy link with sale order lines does not work

### ISSUE THREAD

**Issue by droelneo** [OCA/account-invoicing#139]
In the last part of the do_merge function, the test on self.env['sale.order'] is always False as the object is void.
So, the link with sale order lines is always lost !

**Comment by pedrobaeza** [comment]
Can you point to the line? I have made a recent PR to fix another thing of this module (https://github.com/OCA/account-invoicing/pull/138) and I can include this patch as well.

**Comment by droelneo** [comment]
From line 193 :

```
       # make link between original sale order or purchase order
        # None if sale is not installed
        so_obj = self.env['sale.order']\
            if 'sale.order' in self.env.registry else False
        invoice_line_obj = self.env['account.invoice.line']
        # None if purchase is not installed
        for new_invoice_id in invoices_info:
            if so_obj:
                todos = so_obj.search(
                    [('invoice_ids', 'in', invoices_info[new_invoice_id])])
                todos.write({'invoice_ids': [(4, new_invoice_id)]})
```

**Comment by pedrobaeza** [comment]
Reading code, I see no problem. Are you sure it doesn't work?

**Comment by droelneo** [comment]
The problem is when you assign so_obj = self.env['sale.order'] and the test you do after.

When you test 'if so_obj' will always return False (as it is void)

**Comment by droelneo** [comment]
The test should (for me) become 

-- if obj :
++ if 'sale.order' in self.env.registry:

**Comment by laetitia-gangloff** [comment]
@droelneo the assignation is done on two lines :

```
 so_obj = self.env['sale.order']\
            if 'sale.order' in self.env.registry else False
```

So so_obj is False if sale.order is not in the registry

**Comment by pedrobaeza** [comment]
But he is right, self.env['sale.order'] is evaluated as False. I'll change it.

**Comment by droelneo** [comment]
Thank you @pedrobaeza  !

The object is 'recordset' now, and a void recordset is evaluated as False ;-)

**Comment by laetitia-gangloff** [comment]
Oh ! I learn something, thank you :)

**Comment by pedrobaeza** [comment]
Solved in https://github.com/OCA/account-invoicing/commit/e795b6717bfce340d2f178e4754f290eb95bed79, in the PR https://github.com/OCA/account-invoicing/pull/138
