### ISSUE TITLE
Alternative to account_invoice_supplier_ref_unique v14 without adding a field on account.move

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-invoicing#1484]
In v14, Odoo doesn't display any warning nor any error message when you enter 2 supplier invoices for the same supplier with the same "Bill Reference". In v16, there is a warning banner on the vendor bill when this happens.

In v14, the OCA module **account_invoice_supplier_ref_unique** raises an error when you enter a second supplier invoice for the same supplier with the same number. But this module adds a field "supplier_invoice_number" on account.move, cf:

https://github.com/OCA/account-invoicing/blob/14.0/account_invoice_supplier_ref_unique/models/account_move.py#L11

I think it's a bad design to add a field on account.move that already exists in the native odoo datamodel. Do we have a solution in OCA to have the same feature without adding a field on account.move ?

Otherwise, I think I'll develop one (maybe it will be a backport of the native feature of v16... I don't know yet).

**Comment by sbidoul** [comment]
I remember that at some point Odoo was conflating supplier invoice number and payment reference. I think that was the main reason a new field was introduced. 

If that is resolved a new field may not be necessary anymore.

**Comment by rafaelbn** [comment]
@alexis-via , are you sure? 😄 
 
![imagen](https://github.com/OCA/account-invoicing/assets/8736623/88e339b6-4e2f-45ee-b559-1f6da1940380)

**Comment by etobella** [comment]
@rafaelbn The issue with that, is that if we somehow choose a similar date, the error will not be raised

**Comment by rousseldenis** [comment]
> In v14, Odoo doesn't display any warning nor any error message when you enter 2 supplier invoices for the same supplier with the same "Bill Reference". In v16, there is a warning banner on the vendor bill when this happens.
> 
> In v14, the OCA module **account_invoice_supplier_ref_unique** raises an error when you enter a second supplier invoice for the same supplier with the same number. But this module adds a field "supplier_invoice_number" on account.move, cf:
> 
> https://github.com/OCA/account-invoicing/blob/14.0/account_invoice_supplier_ref_unique/models/account_move.py#L11
> 
> I think it's a bad design to add a field on account.move that already exists in the native odoo datamodel. Do we have a solution in OCA to have the same feature without adding a field on account.move ?
> 
> Otherwise, I think I'll develop one (maybe it will be a backport of the native feature of v16... I don't know yet).

@alexis-via The fact is Odoo core is using the 'ref' field as payment reference. The aim with supplier_invoice_number is to add a reference that is for instance the invoice number at the supplier level that could be (and usually) different from the payment reference.

**Comment by rafaelbn** [comment]
@Shide MT-3840 @moduon

**Comment by sbidoul** [comment]
> The fact is Odoo core is using the 'ref' field as payment reference. 

@rousseldenis I'm confused by your statement.
There is a `payment_reference` field on invoices (it exists since 14 at least).
Is it not used by Odoo for that purpose?
