### ISSUE TITLE
account_invoice_pricelist install into existing database takes excessive time

### ISSUE THREAD

**Issue by gdgellatly** [OCA/account-invoicing#1508]
## Module
account_invoice_pricelist

## Describe the bug
Install of account invoice pricelist takes a very very long time on an existing database.

## To Reproduce
**Affected versions**:
16.0 - likely only v16 as that is where tracking was added

1. Install module into existing database - install logs
```bash
2023-07-13 07:09:35,689 1 INFO mig odoo.modules.registry: module account_invoice_pricelist: creating or updating database tables 
2023-07-13 07:09:35,696 1 DEBUG mig odoo.schema: Table 'account_move': added column 'pricelist_id' of type int4 
2023-07-13 07:09:36,938 1 INFO mig odoo.models: Prepare computation of account.move.pricelist_id 
2023-07-13 07:17:03,625 1 DEBUG mig odoo.schema: Table 'account_move': added foreign key 'pricelist_id' references 'product_pricelist'('id') ON DELETE set null 
2023-07-13 07:17:05,088 1 INFO mig odoo.modules.loading: loading account_invoice_pricelist/views/account_invoice_view.xml 
```
Here we see the computation of pricelist id takes 8 mins. That is OK. I am writing this at 8:12, and it just completed. What it is is the tracking attribute of the pricelist id.

IN pg_activity we see a lot of entries
```sql
       1197 | INSERT INTO "mail_tracking_value" ("create_date", "create_uid", "field", "field_desc", "field_type", "mail_message_id", "new_value_char", "new_value_integer", "old_value_char", "old_value_integer", "tracking_sequence", "write_date", "write_uid") VALUES ('2023-07-13 07:0
9:35.381815', 1, 31160, 'Pricelist', 'many2one', 25129393, 'Retail Pricelist (NZD)', 1, '', 0, 100, '2023-07-13 07:09:35.381815', 1) RETURNING "id"
```
and
```sql
INSERT INTO "mail_message" ("author_id", "body", "create_date", "create_uid", "date", "email_add_signature", "email_from", "is_internal", "message_id", "message_type", "model", "record_name", "reply_to", "res_id", "subject", "subtype_id", "write_date", "write_uid") VALU
ES (2, '', '2023-07-13 07:09:35.381815', 1, '2023-07-13 08:06:26', false, '"X" <auto@localhost>', true, '<751558500365470.1689235586.792078018188477-openerp-message-notify@cd53b85615af>', 'notification', 'account.move', NULL, '"X" <catchall@localhost>', 469036
5, NULL, 2, '2023-07-13 07:09:35.381815', 1) RETURNING "id"
```

**Expected behavior**
A sub 1 hour installation time. The question is how to approach - pre-init hook? Remove tracking? Somehow suspend tracking?

**Additional context**
There isn't actually that many outwards invoices on this database, 530,000.

**Comment by legalsylvain** [comment]
Hi @gdgellatly. I don't see tracked field in this module. https://github.com/OCA/account-invoicing/blob/15.0/account_invoice_pricelist/models/account_move.py
Did i missed something ?

**Comment by gdgellatly** [comment]
Thanks @legalsylvain  Only the version number :) https://github.com/OCA/account-invoicing/blob/d9d2b545e78fffe5bc535054ef5a2aef674a657d/account_invoice_pricelist/models/account_move.py#L16

**Comment by legalsylvain** [comment]
> Thanks @legalsylvain Only the version number :) 

sorry, missed the version !

**Comment by legalsylvain** [comment]
>  A sub 1 hour installation time. The question is how to approach - pre-init hook? Remove tracking? Somehow suspend tracking?

IMO, disable tracking make sense. Traking allow to know when the value changed. For a new computed field, having the date of the installation of the module for all the records is totally useless.
maybe some pseudo code ``my_field._tracking=False`` in the pre-init hook could do the job. (then ``=True``) at the end of the computation.

**Comment by gdgellatly** [comment]
Best I could come up with - I don't really need this now, installed with tracking disabled before writing https://github.com/OCA/account-invoicing/pull/1511
