### ISSUE TITLE
[14.0] account_invoice_mass_sending: Tests failing

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoicing#1528]
They are failing:

https://github.com/OCA/account-invoicing/actions/runs/5786513401/job/15681384050?pr=1524#step:8:178

probably by a change upstream or in dependencies.

Anyway, we need to unblock the situation to get PRs merged, so I have disable the conflicting tests in 914890634fb8820ff8e52113ebe227cd722512e5, while it's fixed by the contributors/maintainers.

**Comment by jguenat** [comment]
Hello @pedrobaeza ,

I think I encoutered this issue when working on #1429  and fixed it in this PR.
Maybe merging it will solve this :)

**Comment by pedrobaeza** [comment]
Great, can you please rebase and reenable the tests to check and let's merge it to normalize the situation?

**Comment by jguenat** [comment]
All green :)

**Comment by pedrobaeza** [comment]
Fixed in #1429
