### ISSUE TITLE
[16.0] account_invoice_fiscal_position_update: error on fiscal position change

### ISSUE THREAD

**Issue by edlopen** [OCA/account-invoicing#1677]
## Module
account_invoice_fiscal_position_update

## Describe the bug
Server error on fiscal position change when the move line hasn't either product nor description.

## To Reproduce
**Affected versions**: 16.0 at least.

1. Create a new invoice.
2.  Add a line without product and description and another line with a product.
3. Go to "Other Info" page and select any fiscal position.

**Expected behavior**
The user should be prompt with a warning and those move lines shouldn't change the tax automatically.

**Comment by edlopen** [comment]
Hello @alexis-via 

I have created [this PR that solves the bug](https://github.com/OCA/account-invoicing/pull/1678). 
Although I would appreciate any suggestions if the solution is not the most appropriate.

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/account-invoicing/pull/1678
