### ISSUE TITLE
MULTIPLE VALUES FOR account.invoice.global_round_line_id: account.invoice.line

### ISSUE THREAD

**Issue by ghost** [OCA/account-invoicing#175]
module: account_invoice_rounding
version: 8.0

**Steps to reproduce**
- make a sale order with multiple lines having subtotal in decimals (eg. 656.35,585.25)
  -confirm the sale order with field Create Invoice field = on delivery order and create the invoice from delivery order

**Current behavior**
error raised
**Expected behavior**
as with only one sale line created

**Comment by JRaiml** [comment]
Anyone solved this issue..
