### ISSUE TITLE
[8.0] travis build is red

### ISSUE THREAD

**Issue by adrienpeiffer** [OCA/account-invoicing#185]
https://travis-ci.org/OCA/account-invoicing/branches

**Comment by adrienpeiffer** [comment]
I'm on it

**Comment by gurneyalex** [comment]
thanks for taking care of this. Do you need help?

**Comment by legalsylvain** [comment]
Still failing.  Do you need help ?

**Comment by NL66278** [comment]
Red Travis can be solved with this PR (that has become a little broader then the title suggests, just in order to fix Travis): https://github.com/OCA/account-invoicing/pull/215
After merging this (please review!), other PR's should be rebased....

**Comment by pedrobaeza** [comment]
I close this issue then and proceed to review + merge this one.
