### ISSUE TITLE
Account invoice block

### ISSUE THREAD

**Issue by ccandito** [OCA/account-invoicing#206]
Dear All,
I've implemented it on version 9.0.
The indicator "no follow up" on vendor bills appears.
I've set it.
Unfortunately, the payment was still possible.
The expected behavior could be the payment is forbidden with this indicator.
Regards
claudio candito

**Comment by pedrobaeza** [comment]
This modules is working as expected. It can be a module conflict. Please try to reproduce it on runbot and then specify the steps. I close this meanwhile.
