### ISSUE TITLE
merge invoices do not work due to commit f333de21ce2878b40f2e5729d8c216c9d9303f07

### ISSUE THREAD

**Issue by geekobi** [OCA/account-invoicing#235]
Hi,
the commit ( @luc-demeyer luc-demeyer committed with pedrobaeza on 21 Jan, f333de21ce2878b40f2e5729d8c216c9d9303f07)
changed the return value of do_merge(...) from account_invoice_merge/models/account_invoice.py :

It was : return invoices_info
and it becomed : return invoices_info, invoice_lines_info
(last line : 221)

but, account_invoice_merge/wizard/invoice_merge.py in merge_invoices(self) line 87 calls it 

    allinvoices = invoices.do_merge(keep_references=self.keep_references,
                                        date_invoice=self.date_invoice)

and remained unchanged

I fixed the issue in probably dirty way by doing 

    (allinvoices, dummy) = invoices.do_merge(keep_references=self.keep_references,
                                        date_invoice=self.date_invoice)

but, as I am quite new in odoo
also because there is a big PR (8.0 account_invoice_merge fixes #220)
	It prefer not going too far and push only an issue

**Comment by luc-demeyer** [comment]
@geekobi 
PR https://github.com/OCA/account-invoicing/pull/220 fixes it, hence it's best that you run with that code until this PR is merged.
