### ISSUE TITLE
[8.0] account_invoice_shipping_address wrong partner

### ISSUE THREAD

**Issue by scigghia** [OCA/account-invoicing#239]
this module in presence of stock_transport_multi_address should transfer the invoice shipping address using right field delivery_address_id from stock.picking

maybe we could add stock_transport_multi_address dependency and use delivery_address_id as proposed

https://github.com/OCA/account-invoicing/blob/8.0/account_invoice_shipping_address/stock.py#L33

**Comment by pedrobaeza** [comment]
Closing as there's a PR for fixing this.
