### ISSUE TITLE
total amount invoice doesn't appear in version 10

### ISSUE THREAD

**Issue by ccandito** [OCA/account-invoicing#244]
Dear All,
After installing the module the total amount does not appear at header level in vendor invoice screen.
I'm working on version 10 and in version 9.0 this feature worked out perfectly.
Regards
thanks in advance
claudio candito

**Comment by pedrobaeza** [comment]
Which module? Is migrated?

**Comment by ccandito** [comment]
no, it has been implemented from scratch
Regards
claudio candito

**Comment by pedrobaeza** [comment]
You haven't still said the module. I close due to lack of information.
