### ISSUE TITLE
[8.0] Exception on merge of supplier invoice with partial delivery of PO

### ISSUE THREAD

**Issue by renzo1974** [OCA/account-invoicing#258]
When merging two supplier invoices, where at least one invoice contains only some positions of a purchase order, an exception is occured:

File "/var/lib/odoo/addons/account-invoicing/account_invoice_merge_purchase/models/account_invoice.py", line 35, in do_merge
    new_invoice_id][org_iline.id])
KeyError: 73

**Comment by gurneyalex** [comment]
fixed by #268
