### ISSUE TITLE
Strange directories in repos

### ISSUE THREAD

**Issue by elicoidal** [OCA/account-invoicing#304]
Should we be worried about:
https://github.com/OCA/account-invoicing/tree/8.0/account_invoice_default_company_bank_partner/i18n
https://github.com/OCA/account-invoicing/tree/8.0/account_invoice_default_company_bank_repair/i18n
https://github.com/OCA/account-invoicing/tree/8.0/account_invoice_default_company_bank_sale/i18n

They seem empty except for some PO files?

**Comment by elicoidal** [comment]
@tafaRU @alexis-via @pedrobaeza

**Comment by pedrobaeza** [comment]
This is a weird side effect of Transifex scripts. I haven't been able to fully trace the problem, but as we are deprecating it, just remove the folders and remove the resources on Transifex.

**Comment by elicoidal** [comment]
@pedrobaeza OK. I will make a PR

**Comment by elicoidal** [comment]
Fixed by #305
