### ISSUE TITLE
[RFC][account_invoice_line_discount_fixed_amount]

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-invoicing#310]
This is an RFC proposing an approach to handing fixed amount discounts in invoices. 
See https://github.com/OCA/sale-workflow/issues/521 for fixed amount discount in sales order lines.

Account Invoice Line Discount Fixed Amount
==================================
* Introduces a 'Discount (Fixed amount)'
* A user cannot enter both a 'Discount (%)'  and 'Discount (Fixed amount)'  (constraint).
* The total invoice amount is computed according to whatever discount type was applied.
* The total invoice tax amount is computed according to whatever discount type was applied.
* The invoice form shows the 2 discount types.

Configuration
------------------
* Go to 'Invoicing / Settings' and check the box "Use fixed amount discounts'. This will ensure that all employees have access to the new field by adding them to group 'Usability / Use fixed amount discounts'.

In order to implement this, we 'd follow a similar approach as https://github.com/OCA/account-invoicing/blob/10.0/account_invoice_triple_discount/models/account_invoice.py

**Comment by pedrobaeza** [comment]
@sergio-teruel shouldn't we have this for product prices (percentage or fixed price)?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza What do you mean for product prices? What product is defined as percentage?

**Comment by pedrobaeza** [comment]
For PrestaShop, you can define sales price as a fixed amount or percentage of cost price. The problem with this comes from rounding errors.

**Comment by JordiBForgeFlow** [comment]
Well, how do you define discounts in prestashop? I am dealing with an integration with Drupal Commerce, where the discount comes as a fixed amount. In the magento connector they have a similar issue, but they translate a fixed amount discount to a % discount in Odoo. https://github.com/guewen/connector-magento/blob/2eb2310476e4a7e9035435e424179b15d1cf458e/connector_magento/models/sale_order/importer.py#L639 This, however, can easily translate into discrepancies between the ecommerce order and the odoo one.

**Comment by pedrobaeza** [comment]
I don't remember if it was PrestaShop or other source, but it's something similar. You will have rounding issues any way, but that's why sale_exception exists.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Why do you mean that sale_exception occurs? In the end you have rounding errors between Odoo and the ecommerce, so I cannot see where sale_exception would help.

On the other side having the ability to add a fixed discount is often needed.

**Comment by pedrobaeza** [comment]
sale_exception is for the cases where there's a rounding error, and thus the sales order total amount is not the same as the sum of line subtotals. If I don't remember bad, Magento connector uses this module for finding the error.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza but you you agree on the need for this module?

**Comment by pedrobaeza** [comment]
Yes, but please include a security group for displaying these fields by user.

**Comment by sergio-teruel** [comment]
About product price, we had rounding errors with taxes calculation with products with taxes includes...
