### ISSUE TITLE
Account_invoice_merge new features??

### ISSUE THREAD

**Issue by JonathanNEMRY** [OCA/account-invoicing#312]
Hello, I need a custom use case from the module account_invoice_merge and I am currently asking myself if this case could be integrated into the community. Here it is:
```
Invoice 1 - to Asusteck Arthur Gomez 
Invoice 2 - to Asusteck James Miller
```
With the current account_invoice_merge you can not merge those invoices because the  partners are differents.
But if you take in consideration that after the merging effect we 'd like to have an invoice only for Asusteck company and not its contacts then the module can not provide the job.

Is there any way to do this with (mayebe) another community module? Otherwise I will implement it soon so just let me know if
* you agree to integrate it here
* you have any fears about any side effects
* you have a better idea to implent this use case...

Many thanks,

-jne

**Comment by pedrobaeza** [comment]
You can add a new option in the merge dialog for allowing that behavior, and modify code according that option.

**Comment by JonathanNEMRY** [comment]
Hello @pedrobaeza  that was the idea, adding a boolean into the wizard making possible to allow diffrent partner if they have the same parent_id. I will run on this way if anyone has a better idea just let me know here. I will make a PR soon
regards,
-jne

**Comment by JordiBForgeFlow** [comment]
IMHO if they have different invoice partners they should never be merged. You can choose to manually correct the invoice partner.

But this also relates to a bad practice (IMHO) in odoo, where the person who asked for an order becomes the invoice partner.

Whoever asks for a sales order or invoice should be the order/invoice contact person. The partner should represents the entity / person that will have the liability

**Comment by JonathanNEMRY** [comment]
@jbeficent  I agree that normaly the correct use case should be setting the partner_id with the sub-contact and the invoice partner id with the parent_id...but taking in consideration that there are many invoices into this case and those invoice are into draft then it could be a good added feature what do you think?
