### ISSUE TITLE
"purchase_stock_picking_return_invoicing" migration in version 10 

### ISSUE THREAD

**Issue by ccandito** [OCA/account-invoicing#321]
Dear All,
I'm not able to find the app "purchase_stock_picking_return_invoicing" in version 10 in the related github section.
Perhaps it has been renamed or merge with another app?
please help me because this has been very useful in version 9.
Regards
claudio candito

**Comment by pedrobaeza** [comment]
It has not been migrated yet.

**Comment by pedrobaeza** [comment]
There's a migration in progress in #283 that you can review (https://odoo-community.org/page/review)

**Comment by ccandito** [comment]
Thanks

Il 18 ott 2017 15:45, "Pedro M. Baeza" <notifications@github.com> ha
scritto:
