### ISSUE TITLE
import account_invoice_refund_option in version 10

### ISSUE THREAD

**Issue by ccandito** [OCA/account-invoicing#345]
Dear All,
it is possible to have the porting of "account_invoice_refund_option" in version 10?
is there some other function implemented instead?
regards
claudio candito

**Comment by pedrobaeza** [comment]
No, this module is not needed (actually, also it's not in v9), because you have the possibility of creating a new refund from options "submenu" in the journal kanban rectangle.

**Comment by ccandito** [comment]
thanks a lot
claudio candito

2017-12-27 8:07 GMT+00:00 Pedro M. Baeza <notifications@github.com>:

**Comment by ccandito** [comment]
Dear Pedro,
sorry for bothering you again, but I did not find the option to create a credit note.
Please help me sending me out a screeshot also.
Regards
claudio candito

**Comment by pedrobaeza** [comment]
Proper place for these questions is the forum, not here. This is the last one I answer.

![seleccion_011](https://user-images.githubusercontent.com/7165771/34916210-9da9c9dc-f934-11e7-93f9-7ecacb015f98.png)
