### ISSUE TITLE
Porting of "account_invoice_search_by_reference" in Odoo10

### ISSUE THREAD

**Issue by ccandito** [OCA/account-invoicing#346]
Dear All,
is it possible to have this feature in version 10 also.
Please help me whether this has been substituted with something else.
thanks in advance
claudio candito

**Comment by pedrobaeza** [comment]
Please don't open issues for each module that you want to have migrated. There's an issue for tracking the progress of the migration. If you are interested in a module, consider to finance someone for migrating it.
