### ISSUE TITLE
error on compute function  

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/account-invoicing#357]
in the  `def compute(self, value, date_ref=False):` there is an error in line 153 on
`  if not float_is_zero(amt, precision_rounding=prec):`
if amt=0,6  the result is true instead of false .
it should-be  
`  if not float_is_zero(amt, precision_rounding=prec, **2**):
                result.append((fields.Date.to_string(next_date), amt))
                amount -= amt` because the float_is_zero need  a value and precision_digits and precision_rounding `float_is_zero(value, precision_digits=None, precision_rounding=None):` to work properly. 

Marco

**Comment by MarcoCalcagni** [comment]
account_payment_term.py file

**Comment by MarcoCalcagni** [comment]
[10]

**Comment by pedrobaeza** [comment]
Please make a PR amending the problem then. This is very hard to read and you don't even mention the module, the version...
