### ISSUE TITLE
account_invoice_supplier_ref_unique - Odoo Version 10

### ISSUE THREAD

**Issue by ccandito** [OCA/account-invoicing#358]
Dear All,
from my perspective, the invoice data should be included also in the check.
in short, two invoices with same vendor code and same reference, but different document date (mainly the year) are not to be set as duplicated.
Regards
claudio candito

**Comment by pedrobaeza** [comment]
I can understand to include a constraint by supplier/number, but not by date. By definition, a supplier mustn't repeat their numbers. I know that there are bad suppliers that each year restart their numbers without including a reference to the year, but this is something that they are doing incorrectly. You can input them with the year included in your Odoo.

**Comment by ccandito** [comment]
Dear Mr Baeza,
by definition a customer mustn't repeat their numbers in a calendar year.
please take into account only some ERP system has the year into the number range, e.g. Odoo can have, but SAP-ECC usually doesn't.
Therefore, it is quite often to have the same invoice number repeated every year, mainly for small vendors (as contingent workers).
Regards
claudio Candito

**Comment by pedrobaeza** [comment]
As said, the strategy is to book the supplier invoice adding that year in your supplier reference.

**Comment by ccandito** [comment]
sorry, which strategy we are speaking about.
this is a missing feature and not a strategy.
regards
claudio candito

**Comment by pedrobaeza** [comment]
OK, as you want.

**Comment by pedrobaeza** [comment]
OK, as you want.
