### ISSUE TITLE
[8.0.][account_invoice_rounding] rounding added twice to amount_untaxed

### ISSUE THREAD

**Issue by BT-tbaechle** [OCA/account-invoicing#377]
Module: account_invoice_rounding
Version: 8.0

Steps to reproduce:
1. (install account_invoice_rounding)
2. In Settings -> Accounting set the following:
![selection_183](https://user-images.githubusercontent.com/26485507/39468888-96a37b56-4d35-11e8-9924-03c16cdc253e.png)
3. Create new customer invoice
4. Add new invoice line and set the unit price to 90.00 and tax 7.7%
5. Save and Validate

The "Rounding" invoice line amount is added twice in the amount_untaxed => 90.04. The strange thing is that this only occurs for specific unit prices, in most cases it seems to work fine.
![selection_184](https://user-images.githubusercontent.com/26485507/39468913-ba34cb2e-4d35-11e8-922a-5f9fbe5dc2de.png)
The total amount is computed correctly but the calculation of the amount_untaxed is wrong.

**Comment by pedrobaeza** [comment]
@yvaucher @hurrinico any tip about this?

**Comment by BT-tbaechle** [comment]
Hi @yvaucher and @hurrinico do you have any idea how to fix this or any thoughts on my suggested fix #378? Thanks a lot.

**Comment by yvaucher** [comment]
@BT-tbaechle hello thanks for reporting, I almost haven't touched this module since I created it in 2014.

I see it definitely is in need of unit tests, but I cannot tell if your fix is the correct one. I'll have a check at your PR though.
