### ISSUE TITLE
[8.0.][account_invoice_rounding] rounding invoice line not removed after tax calucaltion

### ISSUE THREAD

**Issue by BT-tbaechle** [OCA/account-invoicing#379]
Module: account_invoice_rounding
Version: 8.0

Steps to reproduce:
1. (install account_invoice_rounding)
2. In Settings -> Accounting set the following:
![selection_183](https://user-images.githubusercontent.com/26485507/39473638-199a67e4-4d50-11e8-9277-12aeeb329db2.png)
3. Create new invoice
3. Add new invoice line and set the unit price to 47.77 and tax 7.7%
4. Save 

A "Rounding" invoice line with a unit price of -0.02 is created before the tax is calculated (which seems to be correct although it might make more sense to create the rounding line only after the tax is calculated).
![selection_185](https://user-images.githubusercontent.com/26485507/39473680-3fcaf000-4d50-11e8-915e-ea2d7cc069c7.png)

When the tax is calculated, the rounding is no longer necessary and thus is not considered in the amount_untaxed but the rounding invoice line still exists which can cause a lot of confusion.
![selection_186](https://user-images.githubusercontent.com/26485507/39473708-69c95ff4-4d50-11e8-980a-b6b9fcfd680f.png)

**Comment by BT-tbaechle** [comment]
Hi @yvaucher and @hurrinico is this behavior expected? Are the any plans to fix this? I would greatly appreciate it! Thanks a lot.

**Comment by yvaucher** [comment]
I haven't touched the invoices in v8.0 since a while. I don't plan to work on version 8.0.
But if you do a PR as for #377 I'll review it.
