### ISSUE TITLE
[11.0][account_invoice_supplier_ref_unique]Exception even on same number for different fiscal year?

### ISSUE THREAD

**Issue by GSLabIt** [OCA/account-invoicing#383]
Module: account_invoice_supplier_ref_unique

It rise an exception even if the invoice number is same but in different fiscal year, so basically that are different invoice ref.

Step to reproduce:

Create supplier invoice with the same number in different fiscal year. Tested on 11.0 but could happen on other branchs

Possible solution:

Check the fiscal year based on invoice date, if differente don't rise exception

**Comment by pedrobaeza** [comment]
That's not something covered by the module. If you want them to differentiate it, include the year on the number.

**Comment by GSLabIt** [comment]
Well, as you can imagine, i cannot control and force suppliers to include year in the invoice number. 

I'll try to modify the module to take in account the fiscal year instead and send a PR if allowed ..

**Comment by gcobachoesment** [comment]
Hello, we are going to make the change as soon as possible, at least for our use, requested by our financial director, as GSLablt comments, we do not have control over the supplier's invoice number.
