### ISSUE TITLE
[6.1/7.0] invoice_validation_wkfl: draft to cancel transition is broken

### ISSUE THREAD

**Issue by rdeheele** [OCA/account-invoicing#39]
the invoice_validation_wkfl addon breaks the transition between draft and cancel states
because
https://github.com/OCA/account-invoicing/blob/7.0/invoice_validation_wkfl/invoice_wkf.xml#L42
overwrites
https://github.com/odoo/odoo/blob/7.0/addons/account/account_invoice_workflow.xml#L68

**Comment by yvaucher** [comment]
Fixed by #40
