### ISSUE TITLE
[8.0] account_invoice_merge - SO paid checkbox do not work

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-invoicing#42]
I just did a quick test. I created 2 SO with an invoicing policy : on delivery. I delivered and generate invoices.

I merged the 2 invoices (with same partner)...fine 

But on the SO the check box 'Paid' is not checked. 

Is it an know issue ?

Thanks

Frederic

**Comment by pedrobaeza** [comment]
I suppose that in your explanation, you're missing that after merging then, you have paid the resulting invoice, doesn't it?

**Comment by fclementic2c** [comment]
Yes I did. You're right.

**Comment by pedrobaeza** [comment]
Is this still happening with latest version?

**Comment by AaronHForgeFlow** [comment]
Is this still happening? Can we close?

**Comment by pedrobaeza** [comment]
Closing as no answer
