### ISSUE TITLE
[RFC] Select timesheet lines to invoice

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-invoicing#436]
Hi,

I'm looking for a way to select specific timesheet lines to invoices. In 11, as far as I could see, we can only invoice delivered quantities for the SO, but there is no way to precisely select which timesheet lines to invoice.

So I envision an action that you could launch to create an invoice from a list of selected timesheet lines.

Does such a module make sense?

**Comment by sbidoul** [comment]
cc/ @chrisdec

**Comment by pedrobaeza** [comment]
I think it makes sense, but I think is somewhat covered. @rafaelbn you said that this has been introduced. Can you enlighten us?
