### ISSUE TITLE
[REF] account_invoice_change_currency: Change button from header to next to currency field

### ISSUE THREAD

**Issue by moylop260** [OCA/account-invoicing#443]
Currently
 - ![screen shot 2018-10-23 at 22 11 29](https://user-images.githubusercontent.com/6644187/47403853-b1f6f300-d710-11e8-816a-17776d7e042f.png)

RFC
  - Hidde the button if there is not activated the multi-currency settings.
  - Move the header top button to next to currency field with a fancy icon related:
   - ![borrar](https://user-images.githubusercontent.com/6644187/47404011-5416db00-d711-11e8-9018-6b6fd9bc4843.png)

What do you think @novawish?

@hugho-ad Could you help us with this one?

**Comment by hugho-ad** [comment]
here is https://github.com/OCA/account-invoicing/pull/444

**Comment by moylop260** [comment]
and https://github.com/OCA/account-invoicing/pull/446
