### ISSUE TITLE
[12.0][account_invoice_change_currency] The custom_rate field has a bad position in supplier invoices.

### ISSUE THREAD

**Issue by yaniaular** [OCA/account-invoicing#457]
**Supplier Invoice:**

![image](https://user-images.githubusercontent.com/7602170/49261861-7afbb780-f409-11e8-8010-bb2f0928e4de.png)

**Comment by moylop260** [comment]
@hugho-ad 
Could you check it, please?

**Comment by hugho-ad** [comment]
https://github.com/OCA/account-invoicing/pull/458
