### ISSUE TITLE
[12.0] Weblate: Can't translate account_invoice_change_currency

### ISSUE THREAD

**Issue by hugho-ad** [OCA/account-invoicing#466]
There are not any term available to translate at https://translation.odoo-community.org/projects/account-invoicing-12-0/account-invoicing-12-0-account_invoice_change_currency/

![image](https://user-images.githubusercontent.com/10233975/50125135-30fa3a80-022d-11e9-9da3-3e8e764ded29.png)

**Comment by hugho-ad** [comment]
@pedrobaeza 

any clue?

cc: @moylop260

**Comment by moylop260** [comment]
Maybe @sbidoul could help.
Should we create a new issue https://github.com/OCA/maintainer-quality-tools/issues/new?

**Comment by pedrobaeza** [comment]
It's not a question of no strings to translate. It's that there are no language files for now. The problem then is that the button "Comenzar una nueva traducción" (Start a new translation) is not available for you. This is something that happens periodically. I have given again the permission but I think this is going to be reset. @sbidoul did you find why this happens? Maybe after an update? Any way, I have already included spanish for you to start translating.

**Comment by sbidoul** [comment]
At the moment weblate user hugo-ad is only in the Viewers group.

@pedrobaeza what have you changed exactly? This did not happen since we use the `OCA Translator` role?

**Comment by pedrobaeza** [comment]
I have added the permission to "Translation" role without knowing about the other role... I didn't think about not being included in Spanish. Fixing it right now.
