### ISSUE TITLE
[PERF] account_invoice_change_currency: Slow query from domain

### ISSUE THREAD

**Issue by moylop260** [OCA/account-invoicing#469]
The following line of code:
 - https://github.com/OCA/account-invoicing/blob/7cb1413180db0b97d406c966097ac400884f872b/account_invoice_change_currency/models/account_change_currency.py#L115

Run the following sql query:
 - `SELECT mail_message.id FROM mail_message WHERE (mail_message.subtype_id != 58) ORDER BY mail_message.id DESC;`

This is so slow (2s) because the result is too big if you have too many records.
After that will process the result of all ids fetched for a second query, then it is so slow.

@hugho-ad 
Could you help us, please?

**Comment by hugho-ad** [comment]
@moylop260 
FYI
https://github.com/OCA/account-invoicing/pull/470
