### ISSUE TITLE
10.0 - account_invoice_change_currency: Test error

### ISSUE THREAD

**Issue by moylop260** [OCA/account-invoicing#483]
` AssertionError: 2004.64 != 2004.67 : Total amount of invoice does not equal to expected value!!!

https://travis-ci.org/OCA/account-invoicing/jobs/481472498#L1707

@hugho-ad 
Could you help us with this issue, please?

**Comment by hugho-ad** [comment]
@novawish 

could you help us with this issue?

Best regards

**Comment by novawish** [comment]
@hugho-ad I’m really sorry for not awaring of this until now because I did not enable Notifications by mention in my github settings.
It seems that the issue was fixed by https://github.com/OCA/account-invoicing/pull/487, is it ok for now?
If yes can we close this issue?

Thanks and best regards.
