### ISSUE TITLE
erro on installling module account_invoice_refund_link

### ISSUE THREAD

**Issue by abdufarag** [OCA/account-invoicing#508]
Error while importing module 'account_invoice_refund_link': u'"Error while validating constraint\n\nField `refund_reason` does not exist\n\nError context:\nView `Account invoice (customer) | add Refunds details (form)`\n[view_id: 813, xml_id: n/a, model: account.invoice, parent_id: 502]\nNone" while parsing /tmp/tmpxubF2O/account_invoice_refund_link/views/account_invoice_view.xml:8, near\n<record id="view_customer_account_invoice_add_refunds_details_form" model="ir.ui.view">\n <field name="name">Account invoice (customer) | add Refunds details (form)</field>\n <field name="model">account.invoice</field>\n <field name="inherit_id" ref="account.invoice_form"/>\n <field name="arch" type="xml">\n <notebook position="inside">\n <page name="refunds" string="Refunds">\n <group attrs="{\'invisible\':[(\'type\', \'not in\', [\'in_refund\', \'out_refund\'])]}">\n <separator string="Description" colspan="4"/>\n <field name="refund_reason" nolabel="1"/>\n <separator string="Original invoice" colspan="4"/>\n <field name="origin_invoice_ids" nolabel="1">\n <tree decoration-info="state == \'draft\'" decoration-muted="state == \'cancel\'" string="Original invoice">\n <field name="partner_id" string="Customer"/>\n <field name="date_invoice" string="Bill date"/>\n <field name="date_due" string="Due date"/>\n <field name="number" string="Number"/>\n <field name="reference" string="Reference"/>\n <field name="origin" string="Source"/>\n <field name="amount_total_signed" string="Total"/>\n <field name="residual_signed" string="Due"/>\n <field name="state" string="Status"/>\n </tree>\n </field>\n </group>\n <group attrs="{\'invisible\':[(\'type\', \'not in\', [\'in_invoice\', \'out_invoice\'])]}">\n <separator string="Refund invoices" colspan="4"/>\n <field name="refund_invoice_ids" nolabel="1">\n <tree decoration-info="state == \'draft\'" decoration-muted="state == \'cancel\'" string="Refund invoices">\n <field name="partner_id" string="Customer"/>\n <field name="date_invoice" string="Bill date"/>\n <field name="number" string="Number"/>\n <field name="reference" string="Reference"/>\n <field name="origin" string="Source"/>\n <field name="refund_reason" string="Refund reason"/>\n <field name="amount_total" string="Total"/>\n <field name="state" string="Status"/>\n </tree>\n </field>\n </group>\n </page>\n </notebook>\n </field>\n</record>'

**Comment by pedrobaeza** [comment]
The module is working perfectly in fresh DBs. The problem should be yours in your DB with bad inheritance/view changes. Fix that in your DB and it will work.

**Comment by abdufarag** [comment]
I have installed a fresh Odoo vm and worked fine.
Thanks pedrobaeza
