### ISSUE TITLE
Invoice Fiscal Position Update doesn't work ok - Anglo Saxon Accounting

### ISSUE THREAD

**Issue by feketemihai** [OCA/account-invoicing#52]
In anglo saxon accounting when you invoice a reception (receipt) from stock, the account is put as the stock input account in the invoice line...if you change the fiscal position the account is changed to the expense account instead to remain to the stock one...I will prepare a patch for the supplier invoice to take the account already in the invoice line and to map it from fiscal position, if you agree...

**Comment by pedrobaeza** [comment]
Is this still happening?
