### ISSUE TITLE
New Module: Total Discount on Invoice

### ISSUE THREAD

**Issue by agent-z28** [OCA/account-invoicing#539]
Hello we have a module called total_discount.
It provides the possibility to add a total discount on invoice / sale.order.
The result have been accepted by EDEKA / REWE and so on.
Is there any specific reason why i cant find a module about this?
If anyone is interested we can provide this module.

**Comment by pedrobaeza** [comment]
@sbidoul you were working in a module for this, isn't it?

The problem with discounts in totals is the accounting part. First thing is: the aim for the total discount is an early payment discount or any other concept?

**Comment by agent-z28** [comment]
Yes we have the propper solution for the accounting part.
As said, we have neglected with big players, since they only accept it one way.
finally we have it like they expect it.
It's just a default discount, ontop of the bill, that has been contracted with the client.

**Comment by pedrobaeza** [comment]
Can you indicate more details about how it's done for proper documentation (this can be later used in the README of the module)?

**Comment by agent-z28** [comment]
It sounds quite simple, the basic concept is:

We create a discount invoice line with the (negativ) amount.
then we have a new O2M that is being used in the view and report.
invoice_line_without_discount = fields.One2many('account.invoice.line', 'invoice_id', 'Invoice Lines', domain=[('is_discount_line','=',False)])
in the invoice line we have a discount product with the propper account (configureable)

We have had like 20 diffrent use cases with rounding issues only this one fullfilled it.
