### ISSUE TITLE
Any Debit Note module in OCA?

### ISSUE THREAD

**Issue by kittiu** [OCA/account-invoicing#549]
Hi, in v12, there is Credit Note which is working fine. It runs credit note sequence and have reference back to the original invoice (refund_invoice_id).

We are looking for the opposite, which is **Debit Note** and wonder if it exists in OCA?

Note: I understand that **Debit Note** is just the same as invoice but we need to runs the debit note sequence and have reference back to original invoice (debitnote_invoice_id, may be).

Otherwise, please suggest whether we should develop it?

@ps-tubtim, @Saran440

**Comment by kittiu** [comment]
Hi will be doing it as new addon - **account_debitnote**

**Comment by pedrobaeza** [comment]
Why not simply invoices with a different journal and sequence?

**Comment by kittiu** [comment]
The main feature we need is to link the debit note back to original invoice for form printing and some report. The wizard to create it is a plus.

**Comment by kittiu** [comment]
It is done here,
https://github.com/OCA/account-invoicing/pull/559
