### ISSUE TITLE
Payment not allow to net invoice and refund

### ISSUE THREAD

**Issue by wipawii** [OCA/account-invoicing#551]
Hello all, I am functional. As I work on Odoo v12, I found payment allow to make a payment for only one type of invoice. We cannot net payment for invoice and refund.

For example, we issue 10 invoices for customers and customer return defected stock then we issue 1 refund out to a customer. Let say 10 invoices total $1,000 and 1 refund at $10. The customer makes a payment at $990 for 11 documents (10 invoices + 1 refund).

What we are looking for is select Customer to show both types of invoice and refund then select only these 11 documents for matching aforesaid payment.

I may miss some points of Odoo v12. Please suggest. Thanks.

**Comment by pedrobaeza** [comment]
Sorry, but this is not related to any of the modules in this repository, but on Odoo standard, and this is not an issue, but a question. You should do it on official forums or mailing lists.

**Comment by wipawii** [comment]
Thanks. I will move to a mailing list as suggested.
