### ISSUE TITLE
[11] account_invoice_report_grouped_by_picking

### ISSUE THREAD

**Issue by karlggest** [OCA/account-invoicing#576]
Hi.

I tried this module in a test database and seems work fine. But when i tried my working database invoice report don't show picking info.

Where can I look why my invoice reports don't change?

Ty and regards.

**Comment by pedrobaeza** [comment]
It's because in your production DB you don't have the picking links in the invoices, as you have installed the module after doing that invoices.

**Comment by karlggest** [comment]
Hi.

I  try this as follow:

1. Uninstall account_invoice_report_grouped_by_picking and stock_picking_invoice_link.
2. Update account module.
3. Install account_invoice_report_grouped_by_picking and stock_picking_invoice_link.
4. Make a sale order and confirm.
5. Validate picking.
6. Create invoice.
7. Section picking contains picking info
8. Print doesn't show picking info.

I only need understand where can I try if inheritance works with my reports.

Ty.

**Comment by pedrobaeza** [comment]
Then the problem is in your customization over invoice report. I can't help you more and it's your duty to check sources for knowing the inheritance chain.
