### ISSUE TITLE
[12.0] Bug with account_invoice_pricelist

### ISSUE THREAD

**Issue by jlaloux** [OCA/account-invoicing#592]
With module account_invoice_pricelist installed.

Create an invoice with a specific pricelist.

Create a new invoice line with an article having a different price on the form view than in the pricelist.

You'll see you don't get the price from the pricelist but the price from the product view 'standard price or lst_price' in function of the invoice type).

The reason is that the on change on UOM is done after the onchange of the product and the price is recomputed in Odoo standard code with this price and not the pricelist price. If you change again the product to select the same one on the already created invoice line. The price is correctly set because UOM is not redefined.

![ticket_oca](https://user-images.githubusercontent.com/7678583/64341340-6f689d00-cfe8-11e9-9eef-e9f8b25211b7.png)

Thank you,

Regards,

Julien

**Comment by mayjo79** [comment]
+1
