### ISSUE TITLE
[ADD] account_invoice_refund_reason

### ISSUE THREAD

**Issue by max3903** [OCA/account-invoicing#610]
This module allows you to define a list of reasons to create a credit note from an invoice and report on them.

# Configuration

* Go to Accounting > Configuration > Management > Refund Reasons
* Create the different reasons you want to provide users

# Usage

## Operations

* Go to Accounting > Customers > Invoices (or Accounting > Vendors > Bills)
* Select an open invoice (or bill)
* Click on the "Add Credit Note"
* Select the reason and create the credit note

## Reporting

* Go to Accounting > Reporting > Management > Invoices
* Group by refund reason

# Technical specifications

## account.invoice.refund.reason

- [ ] Add a required char field "Name" (name). Make the field translatable.

## account.invoice

- [x] Add a many2one field "Reason" (reason_id) to account.invoice.refund.reason
- [ ] Show it on the refund if the field is set

## account.invoice.refund

- [x] Add a many2one field "Reason" (reason_id) to account.invoice.refund.reason
- [x] Set the existing "Reason" field (description) with reason_id.name
- [x] Hide the existing "Reason" field (description)
- [ ] Push the value to the created refund

## data

- [x] account.invoice.refund.reason.csv:
```
id,name
refund_reason_cancellation,Cancellation
refund_reason_noref,Invoice without reference
refund_reason_error,Lease and/or Minimum Charge Error
refund_reason_agreement,Commercial and/or Collection Agreement
refund_reason_difference,Price Difference
refund_reason_correction,Data Correction
refund_reason_others,Others
```

**Comment by pedrobaeza** [comment]
You can check for similarities in code in https://github.com/OCA/crm/tree/12.0/crm_phonecall_summary_predefined
