### ISSUE TITLE
[RFC] account_invoice_required_tax - required + unique tax per group

### ISSUE THREAD

**Issue by yvaucher** [OCA/account-invoicing#621]
An invoice line must always come with a VAT tax.
This is the idea of the module https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_tax_required
An error on validation forbid to validate an invoice that doesn't has at least one tax per line.

Camptocamp intent to implement the following 3 aspects to improve this module.
First for version Odoo 10.0 and to forward it to newer versions too.

### 1. Uniqueness of tax

The first flaw we can see is that you can still add too many taxes.
I see no reason to add a VAT 6% and a VAT 21% on the same line for the same product.
When dealing with lot of different taxes in addition to VAT, this could be an easy human error either on the invoice or on the product configuration.

Proposal:  A configuration on account.tax.group to force a unique tax inside a group of tax. Assuming all VAT taxes are in the same group.

Implementation:

Add a boolean field on account.tax.group

field_name: unique
default: True

Add the following check:
Check for each line that only one tax is use per group with unique = True

### 2. Define which taxes are required

Currently you just have to set a tax. Whichever tax will do. With many type of taxes you could easily end up with invoice lines without any VAT. Thus you could end up with a non required tax.

Proposal:  A configuration on account.tax.group to define which tax are required based on group. Assuming all VAT taxes are in the same group. You will most probably have only one tax group with required flag. This will define that at least one tax from this group must be selected.
Assuming all VAT taxes are in the same group.

Implementation:

Add a boolean field on account.tax.group

field_name: required
default: False

Refactor the check to ensure there is at least one tax per line of the required group.

### 3. Split module

This feature could also be used on Sale order. Thus, we will have the current module split in 2 and an additional one for sale orders.

```
base_tax_required/
├── account_invoice_tax_required
└── sale_order_tax_required
```

Note: The main assumption is that group of tax are always used to group type of taxes like all VAT taxes in the same group. What is your input on this? Do you have tax group like "VAT" or tax group by percentage like "Tax 15%" in Odoo demo data?
Option could be done on company with list of taxes or tax groups. But to me if groups are used by type of tax as the assumption is, it makes things much easier for requirement and for uniqueness.

@OCA/accounting-maintainers 

cc account_invoice_tax_required authors/contributors
@Nikul-Chaudhary
@angelmoya
@jctrey
@jvpascual
@kittiu
@pedrobaeza
@vrenaville
@mreficent

**Comment by pedrobaeza** [comment]
About 1 and 2, they are out of scope IMO of this module, and it doesn't apply to for example Spanish localization, where tax groups are not conformed the way you are mentioning. I would put then as extra modules. Maybe for v13 you can call it `account_invoice_tax_constraint`.

About 3, I don't see too much right now to be reused from one model to another for justifying 3 modules. Adding the other 2 features can then justify the base module.

**Comment by yvaucher** [comment]
@pedrobaeza thanks for your feedback.

Relying on groups might not be the right path.

IMO point 2 is the most important one. You don't want random taxes to be applied.

**Comment by pedrobaeza** [comment]
Well, for me the correctness of the taxes is given by fiscal position + product original taxes. Maybe an `account_invoice_product_required` module? :stuck_out_tongue:

**Comment by yvaucher** [comment]
@pedrobaeza The idea is to detect that your product original taxes are badly configured and that nothing messed with those settings. Especially with some automated creation of sale order/invoices.

**Comment by pedrobaeza** [comment]
Shouldn't you put that check on the product creation then?

**Comment by yvaucher** [comment]
Then you would have to forbid any modification of taxes on invoices. Plus, products are very generic objects.

**Comment by pedrobaeza** [comment]
Well, I don't see this fitting in the module as said, but if others think so, proceed the way you think.
