### ISSUE TITLE
Error to calculate price subtotal of the invoice line

### ISSUE THREAD

**Issue by cramosh** [OCA/account-invoicing#641]
The account_invoice_triple_discount module fails to calculate the subtotal of the invoice line

For example, when calculating quantity 400 and unit price 1.5 with a discount of 15, the result returns 512 when it should be 510.

If we apply a 25% it returns 452 when it should be 450. But if we apply a 50% or even discount it calculates it well.

The decimal precision of the unit price is 2 if we set it to 3 it calculates well.

The tests have been carried out in the runbot of the OCA version 11

**Comment by pedrobaeza** [comment]
You are not indicating Odoo version, but check #517 that probably fixes your problem.

**Comment by igallart** [comment]
I have checked, it happens in version 10 and 11 (12 and 13 I don't know). With #517 I haven't tried.

**Comment by igallart** [comment]
In V12 of runbot it fails:

![imagen](https://user-images.githubusercontent.com/13520529/70034826-1cd05a00-15b2-11ea-94f8-dfd881c4a119.png)

**Comment by infoitservit** [comment]
Error still there!
