### ISSUE TITLE
[13.0] [BUG]"account_invoice_fixed_discount" module > Error when adding  "Product lines on invoice form

### ISSUE THREAD

**Issue by NCS-75** [OCA/account-invoicing#670]
When trying to add "product" _(mean move line)_ on invoice form _(customer or supplier)_ . There is an error message :

> TypeError: _get_fields_onchange_balance_model() missing 1 required positional argument: 'price_subtotal'

@kongrattapong 
Context : OCB 13.0 Odoo Server up to date (01/21/2020), with Virgin database , to reproduce issue faced on my test environnement.
- "account_invoice_fixed_discount" module, up to date,  from "https://github.com/OCA/account-invoicing/tree/13.0/account_invoice_fixed_discount"

![account_invoice_fixed_discount-1](https://user-images.githubusercontent.com/59052920/74263235-b75dbf80-4cfe-11ea-998c-d0e24a1d89d4.png)

**Comment by kittiu** [comment]
cc @kongrattapong

**Comment by kongrattapong** [comment]
@NCS-75 This issue fixed by https://github.com/OCA/account-invoicing/pull/663

**Comment by kittiu** [comment]
@NCS-75 is the #663 ok? Can I close this?

**Comment by NCS-75** [comment]
@kittiu Looks good to me, you can close Thanks
