### ISSUE TITLE
13.0 [ADD] Account Move Tier Validation

### ISSUE THREAD

**Issue by pegonzalezspesol** [OCA/account-invoicing#672]
Proposed next PR #674 

This module extends the functionality of Account Invoice to support a tier validation process.

### Installation
This module depends on `base_tier_validation`. You can find it at [OCA/server-ux](https://github.com/OCA/server-ux)

### Configuration
To configure this module, you need to:

Go to Settings > Technical > Tier Validations > Tier Definition.
Create as many tiers as you want for Account Move model.

### Usage
To use this module, you need to:

1. Create an Account Invoice triggering at least one "Tier Definition".
2. Click on Request Validation button.
3. Under the tab Reviews have a look to pending reviews and their statuses.
4. Once all reviews are validated click on Post.

### Additional features:

- You can filter the Account Invoices requesting your review through the filter Needs my Review.
- User with rights to confirm the Account Invoice (validate all tiers that would be generated) can directly do the operation, this is, there is no need for her/him to request a validation.

**Comment by kittiu** [comment]
Close as the PR is merged.
