### ISSUE TITLE
Sales order refunds and purchase order refunds are not linked to the table

### ISSUE THREAD

**Issue by qzmxs** [OCA/account-invoicing#684]
module: account_invoice_refund_link
version: 12.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**
Hope to increase data on sales order refunds and purchase order refunds later

**Comment by pedrobaeza** [comment]
That are not refunds of invoices, so it's normal that they are not shown.

Closing as expected behavior.
