### ISSUE TITLE
[RFC] Contribute Avatax Connector to the OCA

### ISSUE THREAD

**Issue by dreispt** [OCA/account-invoicing#687]
Avalara Avatax is cloud service to computes sales taxes.
In the US it is an alternative to Tax Cloud, that has an EE-only connector.
Additionally, the service supports VAT calculation in the EU space, although that's not currently implemented for Odoo.

This was originally developed by Odoo SA.
They lost interest in maintaining it, invited OSI to maintain it, and we have been doing that since version 12.

Lear more at: https://apps.odoo.com/apps/modules/12.0/avatax_connector/
Current repo is at https://github.com/sodexis/avatax_connector

I would like to contribute this to the OCA, and propose it for this repo.

Comments, questions?
Thanks

**Comment by pedrobaeza** [comment]
I think this is great, but I think it should be located in OCA/l10n-usa, not here, as this is something specific of that country. See also https://github.com/OCA/l10n-usa/pull/47 for an alternative provider.

**Comment by dreispt** [comment]
Thank you Pedro.
Right now it also supports Canada, but the Avatax service also supports EU VAT, and it could be very helpful for eCommerce businesses, with the new EU VAT rules. 

That's why I don't think the US localization is a good host.

**Comment by pedrobaeza** [comment]
OK, then if that's the case, indeed we should go for a neutral one.

**Comment by dreispt** [comment]
Getting back to this, I believe that https://github.com/OCA/account-fiscal-rule would be a more a more on topic host for this feature. I'll propose this there.

**Comment by dreispt** [comment]
👉  https://github.com/OCA/account-fiscal-rule/issues/108
