### ISSUE TITLE
[12.0]purchase_stock_picking_return_invoicing，Conflict with other modules

### ISSUE THREAD

**Issue by qzmxs** [OCA/account-invoicing#692]
module: purchase_stock_picking_return_invoicing
version: 12.0

**Steps to reproduce**
- ...
 purchase_stock_picking_return_invoicing with [purchase_deposit] Conflict modules

There is no problem installing these two modules separately. If the combined installation prevents the (product) bill from being created, you can only create (prepay) the product.
**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Please put real steps to reproduce the problem, apart from installing both modules.

**Comment by qzmxs** [comment]
![image](https://user-images.githubusercontent.com/55458897/77096238-03142f00-6a4a-11ea-864f-6cf2cc05244a.png)
![image](https://user-images.githubusercontent.com/55458897/77096321-24751b00-6a4a-11ea-8339-36a018d627a4.png)
![image](https://user-images.githubusercontent.com/55458897/77096407-45d60700-6a4a-11ea-9de9-95a2db949f7e.png)
![image](https://user-images.githubusercontent.com/55458897/77096909-f80dce80-6a4a-11ea-8aee-e707a36fde3a.png)
![image](https://user-images.githubusercontent.com/55458897/77097084-360af280-6a4b-11ea-83b6-288667541be7.png)

**Comment by qzmxs** [comment]
Differences between the last 2 pictures

**Comment by qzmxs** [comment]
A product setting value
![image](https://user-images.githubusercontent.com/55458897/77097647-13c5a480-6a4c-11ea-90dd-6c6aec5fd7a5.png)

**Comment by qzmxs** [comment]
Prepaid product settings
![image](https://user-images.githubusercontent.com/55458897/77098205-f2b18380-6a4c-11ea-9df6-a828f8286165.png)

**Comment by kittiu** [comment]
Hi, I am the one doing purchase_deposit. Still I can't follow your case, what is the problem?
