### ISSUE TITLE
12.0 branch broken (travis) account_menu_invoice_refund

### ISSUE THREAD

**Issue by legalsylvain** [OCA/account-invoicing#693]
Hi all,

I try to make PR against this repository on 12.0 and I see that there are some troubles with a module named ``account_menu_invoice_refund``.

General view : https://travis-ci.org/github/OCA/account-invoicing/builds/661437675
error : https://travis-ci.org/github/OCA/account-invoicing/jobs/661437677#L1590

@ Authors : Could you take a look ? 
@badbole, @pedrocasi, @kittiu, @OCA/accounting-maintainers 

thanks !

**Comment by AaronHForgeFlow** [comment]
I'd be glad to review that PR. Thank you!

**Comment by kittiu** [comment]
Hi, now I got the same error when I pull latest Odoo 12. I will make the PR on account_menu_invoice_refund to fix it first.
https://github.com/OCA/account-invoicing/pull/695
