### ISSUE TITLE
[12.0] account_menu_invoice_refund: Shouldn't include feature for payments

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoicing#705]
The module should include only the menu part, and not the feature of allowing to mix both invoice types in payments, due to the following reasons:

- I want the first thing (the menu), but not the second, and I'm forced to used both.
- The module name and initial scope don't include the second feature.
- The second feature doesn't belong here (it's a payment feature).
- The monkey-patch technically is conflicting and I prefer to avoid it in my set of modules.

@kittiu can you please check my reasoning?

**Comment by kittiu** [comment]
@pedrobaeza 

In fact, the reason of doing this module is for making netting payment.
But I do understand your concern, and there is another module account_payment_netting
https://github.com/OCA/account-financial-tools/tree/12.0/account_payment_netting
What if I propose,

1. Reduce this account_menu_invoice_refund as you suggest.
2. Add this feature to account_payment_netting, and as such, it need to depend on this one.

Than, account_payment_netting will be by its name, more netting scenario.

WDYT?

**Comment by pedrobaeza** [comment]
Good for me, thanks.

**Comment by kittiu** [comment]
https://github.com/OCA/account-invoicing/pull/707
Next I will move the missing feature to account_payment_netting

**Comment by kittiu** [comment]
After looking into the code, I decide not to move the hook to account_payment_netting
https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_payment.py#L111
This line wasn't exists before, it can break if user using different version of odoo 12.
You are right @pedrobaeza :+1:
