### ISSUE TITLE
Question : account_invoice_refund_link

### ISSUE THREAD

**Issue by svalaeys** [OCA/account-invoicing#706]
This is a question about whether the functionality I coded belongs in this module or not.

This module tracks links between invoices and refunds when the seconds ones were created from the first ones in Odoo. 

There are many cases when such a simple relationship cannot be established. The most complex one is when multiple refunds reconcile with multiple invoices. I know this sounds crazy but it's actually the case I am facing. 

The adjustments needed are not that difficult to code. In the invoice field payment_move_line_ids, all that needs to be done is to look for lines linked to refunds. However, it does mean that the field refund_invoice_ids isn't useful as it does not encapsulate all refunds linked to invoices. 

The functionalities in this module are still very useful in any case because when the refund was indeed created from the invoice, it is really useful to have everything as is.

My question is, should my use case be solved by this module, or does it belong somewhere else?

**Comment by pedrobaeza** [comment]
I think it belongs to other module, as what you describe is not something feasible with standard Odoo, so you need another set of modules for achieving it AFAIK.
