### ISSUE TITLE
User session closed in Odoo 13 with account_invoice_force_number

### ISSUE THREAD

**Issue by jadelaop** [OCA/account-invoicing#711]
In Odoo 13 account_invoice_force_number module disconnects user session every 30 seconds.

**Comment by pedrobaeza** [comment]
I really doubt that module is the guilty of your disconnection. Please try on the runbot link on the README to see if you get disconnected the same there.

**Comment by jadelaop** [comment]
I disabled account_invoice_force_number and now I have no problem.

If I re-enable it, I have disconnections. How I can help you to debug the problem?

I have Odoo 13 on Ubuntu 18.04.

Thank you.

**Comment by pedrobaeza** [comment]
Try it on runbot.
