### ISSUE TITLE
[RFO] New asynchronous invoice mailing module

### ISSUE THREAD

**Issue by manuelregidor** [OCA/account-invoicing#712]
Hi,

I have developed a new module that allows to send emails asynchronously when they contain invoices. It automatically sends emails asynchronoysly when we select the option "Send & print" and more than one invoice has been selected.

You can check out the README file here: https://github.com/sygel-technology/sy-account-invoicing/tree/13.0/asynchronous_invoice_email

Do you find it interesting enough for the OCA?

Thank you

**Comment by kittiu** [comment]
@manuelregidor sure I think someone might find it useful on some case. To me, it is interesting.
You can try making the PR, and I am sure you will get good comments whether or not it is merged finally.
WDYT?

**Comment by manuelregidor** [comment]
> @manuelregidor sure I think someone might find it useful on some case. To me, it is interesting.
> You can try making the PR, and I am sure you will get good comments whether or not it is merged finally.
> WDYT?

You can find the PR here: https://github.com/OCA/account-invoicing/pull/767
Thank you
