### ISSUE TITLE
This is the function I really really need in odoo - Thank you!!

### ISSUE THREAD

**Issue by joergstrohmeier** [OCA/account-invoicing#721]
Great work.
How can I donate?

**Comment by pedrobaeza** [comment]
Which module? Thanks for your offering about donating. You can donate converting into OCA member (https://odoo-community.org/shop/product/20-msm-2020-oca-member-4964) if it's OK for you.

**Comment by joergstrohmeier** [comment]
Dear Pedro,
 
I am using your module "Timesheet details invoice".
 
Then I will buy the membership if this helps you.
 
I am new in odoo, and I start to love it.
 
Freundliche GrüsseJörg Strohmeier

-----original message-----From: "Pedro M. Baeza" <notifications@github.com>Sent: 31 May 2020 18:26To: OCA/account-invoicing <account-invoicing@noreply.github.com>Cc: joergstrohmeier <joerg.strohmeier@gmx.net>; Author <author@noreply.github.com>Subject: Re: [OCA/account-invoicing] This is the function I really really need in odoo - Thank you!! (#721)</author@noreply.github.com></joerg.strohmeier@gmx.net></account-invoicing@noreply.github.com>


 
Which module? Thanks for your offering about donating. You can donate converting into OCA member (https://odoo-community.org/shop/product/20-msm-2020-oca-member-4964) if it's OK for you.

**Comment by pedrobaeza** [comment]
Great, I'm glad you like it. Being membership you help the underlying organization that allows all of us to collaborate in these repositories, putting infrastructure and tools for that. Check https://odoo-community.org/ for more information.

**Comment by joergstrohmeier** [comment]
Hi Pedro

I am now also invoicing expenses and it seems that the details for the 
invoice lines come from your extension. Thats nice.
The only thing I would like to change is the date of the expenses. It 
should be the date when the expense was incurred.

PS: On the timesheet details it would be useful to also show the 
employee who did the hours.



Freundliche Grüsse
Jörg Strohmeier

------ Original Message ------

**Comment by pedrobaeza** [comment]
But AFAIK, you should do that changing the analytic entry date. Anyway, let me close this that is not an issue of the module.
