### ISSUE TITLE
account_invoice_force_number

### ISSUE THREAD

**Issue by nacho22martin** [OCA/account-invoicing#76]
Odoo version 8.0 / Ubuntu 14.10

I've install account_invoice_force_number module and it won't show me the "force number" option on my invoice form.

**Comment by siewemarcelin** [comment]
I can't install account_invoice_force_number module.  It generated me this error during installation:
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<field name="internal_number">' cannot be located in parent view

Error context:
View `account.invoice.form.int_number`
[view_id: 1329, xml_id: account_invoice_force_number.account_invoice_form_int_number, model: account.invoice, parent_id: 809]" while parsing file:///C:/addons/account_invoice_force_number/invoice_view.xml:5, near
<record model="ir.ui.view" id="account_invoice_form_int_number">
            <field name="name">account.invoice.form.int_number</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="arch" type="xml">
                <field name="internal_number" position="attributes">
                    <attribute name="attrs">{'invisible': [('state', '!=', 'draft')]}</attribute>
                    <attribute name="string">Force Number</attribute>
                    <attribute name="help">Force invoice number. Use this field if you don't want to use the default numbering</attribute>
                    <attribute name="invisible">0</attribute>
                </field>
            </field>
        </record>

Somebody can help me please??

**Comment by eLBati** [comment]
Hello,
just went to
http://3110858-8-0-edfe5e.runbot1.odoo-community.org
selected `3110858-8-0-edfe5e-base` DB and installed the module without problems.
Then, I created invoice `12345` forcing its number using this module.

Please be sure you are using the last revision of https://github.com/OCA/account-invoicing and https://github.com/odoo/odoo

Thanks
