### ISSUE TITLE
[12.0] Is there an addon to auto-invoice the orders?

### ISSUE THREAD

**Issue by victoralmau** [OCA/account-invoicing#760]
Suppose we have 100 orders to be invoiced daily (some we do not know if they are, since we do not know if the stock_picking are done), the process could be done manually but we would have to filter which orders are fully invoiced (if the billing policy is to units delivered) but I think an addon that auto-creates these invoices (and groups them by clients if there are 2 or + orders from a client on the same invoice) and auto-validates them would be useful.

Is there a similar addon and / or would this functionality be useful for the community?

**Comment by pedrobaeza** [comment]
There's #755, but not sure about the genericity / integration with other OCA modules.

**Comment by victoralmau** [comment]
I will review this topic in detail as it is very interesting (even if it is only for V13).

The addon that I suggested was quite similar although thinking not about billing once a month, but once a day, everything that is sent is billed (perhaps it would apply to any business logic in Odoo whether or not it has e-commerce).

**Comment by victoralmau** [comment]
Hello, reviewing the addon https://github.com/OCA/sale-workflow/tree/13.0/sale_automatic_workflow and seeing that auto-invoice is possible according to the parameters that you want to configure (custom filters) I think this question is resolved and it would not be necessary to add any addon because _sale_automatic_workflow_ already does it.
