### ISSUE TITLE
[12.0] Is there an addon to auto-pay the invoices?

### ISSUE THREAD

**Issue by victoralmau** [OCA/account-invoicing#761]
Suppose for a sale_order 2 payment_transaction done are linked, the order is confirmed and self-invoiced via https://github.com/OCA/account-invoicing/issues/760.
Let's consider this issue: https://github.com/OCA/account-payment/pull/340 whereby a payment_transaction donated auto-creates an account_payment

A useful functionality I think it could be that when validating the invoice it looks for the sale_order_ids it comes from, and hence the account_payment linked to the payment_transaction done of those sale_orders, we should auto-link those payments to the invoice and give the invoice as paid or partially paid.

Is there this functionality and / or would it be useful for the community?

**Comment by pedrobaeza** [comment]
I'm seeing that most of the flows you are describing (for e-commerce), are already covered in https://github.com/OCA/sale-workflow/tree/13.0/sale_automatic_workflow

**Comment by victoralmau** [comment]
Hello, thanks for your answer, I have looked in detail at that addon. Specifically regarding auto-pay the invoices that I commented if I'm not mistaken, there is the following at the odoo level:

https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L855
https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L791

This process is thinking for a payment to be auto-created when a transaction is linked to an invoice.

**[Idea improves current process]**
I think it would be an optimal process, auto-assign that payment to that invoice (the invoice would be partially or totally paid according to the amount of the transaction)

**Now suppose another "similar" process**
A sale_order is created, the client sees it on the website and decides to "pay", when the payment is completed "nothing" happens and I think adding to the process defined at https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L791 you could also search if there are related sale_order_ids and create the account_payment (same as for invoice); Also, if the amount of (completed) transactions for that order equals the total of the sale_order, auto-confirm it.

**[Idea improves current process auto-validate invoice]**
When an invoice is validated (the one created from the sale_order that has been given as an example) nothing currently happens, but I think the transaction payment / s of the sale_order_ids related to the invoice should be auto-linked to give the invoice as partially or fully paid.

Do you think it is a good idea and can you create an addon for it?
