### ISSUE TITLE
Am I doing something wrong? Missing steps

### ISSUE THREAD

**Issue by tommy1441** [OCA/account-invoicing#763]
Hi, what I understand this addon to do is:
- From the hours i have input in Timesheet for a project X, I can in Sales automatically create an invoice using those hours, importing them from timesheets in other words, so I don't have to manually input them again there.

If this is what it does, then I am unable to do it.
Usage explains to:

_Go to Sales -> Orders -> Orders and create a new Sale Order.
Add line selecting a product with
Product Type -> Service
Service Invoicing Policy -> Timesheets on tasks
Service Tracking -> Create a task in sales order’s project
Confirm Sale
Go to Timesheets -> Timesheet -> My Timesheets and create line with same project of SO and the related task
Go to the Sale Order and select Other Information -> Timesheet invoice description
Create Invoice_

However, from the last step of "Go to the Sale Order and select Other Information -> Timesheet invoice description" I'm not sure how to proceed. Timesheet invoice description is a dropdown, not a button, so I'm not sure what the instructions are saying I need to do. But anyway, I pick one from the dropdown and then... I try to make invoice, but it doesn't work?

I probably am doing something wrong or misunderstanding something, I'd appreciate some clarification. 
It's I imagine too much to ask, but a vid showing the steps would be ideal.
Thank you,

**Comment by kittiu** [comment]
Hello, are you talking about some specific module in this repository you are working on?
Or this is generic Odoo, how to, question?

Thanks!

**Comment by tommy1441** [comment]
@kittiu HI, i'm talking about the account-invoicing addon for odoo 13. I just can't figure out how to make the addon do what it's means to do.
