### ISSUE TITLE
[13.0] account_invoice_fixed_discount: tax computation issue after applying a fixed discount

### ISSUE THREAD

**Issue by Webimtech** [OCA/account-invoicing#818]
Hi,
I need a help please!
The module do not compute the new tax amount after applying a fixed discount.

![image](https://user-images.githubusercontent.com/66035639/99573358-4c9c8b80-29d6-11eb-9a4a-6758db8e21dd.png)

Thank you a lot!

Regards,

**Comment by SalouaSahnoun** [comment]
Hello @Webimtech ;

Please did you find a solution ?

**Comment by Webimtech** [comment]
Hi @SalouaSahnoun 

Actually not ! 
But I noticed that the problem appears when there is no hand action on the fix discount value (in case of quotation to invoice transfer).

If you try to modify the discount value by hand, in this case the module works well..

I hope that the OCA will take the action ...

Regards,

**Comment by Webimtech** [comment]
@pedrobaeza 
Sorry to tag you, I'm not sure who to talk to about this one. It seems like a critical bug is blocking the update of the tax amount if the invoice is created from a quotation: sale.order --> account.move

Could you please get a look on this bug?

Thank you for your help

**Comment by pedrobaeza** [comment]
Sorry, I don't use this module. Ping original authors.

**Comment by SalouaSahnoun** [comment]
@eficent @Rattapong @ballester @ForgeFlow

**Comment by flotho** [comment]
duplicate of #1107
