### ISSUE TITLE
account_invoice_shipping_address Can't create invoice from delivery

### ISSUE THREAD

**Issue by george-andrei** [OCA/account-invoicing#83]
Hello,

First I wanted to thank you for this brilliant module!
Unfortunately I've run into some problems, I think it's a bug because I tried different methods to get it done, and nothing worked.

So here is my problem, when I try to generate the invoice from the delivery I get this error:

  File "/opt/odoo/addons/account_invoice_shipping_address/stock.py", line 32, in _get_invoice_vals
    if picking and picking.partner_id:
AttributeError: 'unicode' object has no attribute 'partner_id'

If I generate the invoice from the SO, it work as it should be. 
My problem is that I can't always create the invoice from the SO because I need the delivery note as source document on the invoice.

You should know that the address type for the delivery is “Shipping”, and it’s not a company, it’s a child of a company. The main company is a standard and regular one (it's the invoice address).

Thank you very much!

Kind regards,
George.

**Comment by eLBati** [comment]
Hello,
I am not able to generate the error on
http://2949055-81-ba9638.runbot2.odoo-community.org
I created SO008, WH/OUT/00007 and SAJ/2015/006 without errors

What versions are you using? What are the steps to reproduce the problem on a new DB?
Thanks
