### ISSUE TITLE
[13.0] purchase_stock_picking_return_invoicing issue with down qty on inv

### ISSUE THREAD

**Issue by sergioeix** [OCA/account-invoicing#863]
With purchase_stock_picking_return_invoicing installed you cant downgrade qty on invoice and create a new one with pending qty from purchase as normal flow.

Steps to reproduce:
1 make a purchase with a product 100 und
2 recive picking all und
3 create bill and down qty to 20 and post
4 back to purchase and then create a bill again, only show the already created bill and dont allow to create a bill for the remain qty

Spected behaivor:
create a new bill with 80 qty

tested on runbot, once purchase_stock_picking_return_invoicing unistalled flow works as spected

Ty

**Comment by pedrobaeza** [comment]
Just click on the "Create" button in the invoice form?

**Comment by sergioeix** [comment]
Hi Pedro you are rigth, now i feel a bit ...   :P 
I think it will be a good idea to mention this on the readme module file because normal flow is diferent without purchase_stock_picking_return_invoicing installed
Ty Sir

**Comment by pedrobaeza** [comment]
You are free to open a PR improving documentation. Meanwhile, I close this issue as it's not.
