### ISSUE TITLE
[13..0]account_group_invoice_line

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/account-invoicing#864]
Hi there

Have you thought about migrating this module for versions from v13?

The accountants that all their invoices that have more than 200 lines and make 5000 invoices a year, checking the invoice entry and then printing the journal at the end of the year can be millions of records.

More than one we are wrong to say.

You have no problems with this?

**Comment by francesco-ooops** [comment]
@pedrobaeza as far as you know, is there any other module in versions 13/14 providing the same features as account_group_invoice_line or does it need porting to 13 and 14?

Thanks!

**Comment by pedrobaeza** [comment]
No, there isn't any, and my advice is that you don't do such thing.

**Comment by francesco-ooops** [comment]
> No, there isn't any, and my advice is that you don't do such thing.

why so? I wouldn't port it myself obviously.

**Comment by pedrobaeza** [comment]
You need to completely change the way Odoo works now (an invoice is the journal entry itself), for no real gain. There's no problem in having millions of journal items.

**Comment by francesco-ooops** [comment]
> You need to completely change the way Odoo works now (an invoice is the journal entry itself), for no real gain. There's no problem in having millions of journal items.

Thanks a lot for the explanation. 
It's not easy to assess whether a module should be ported to the next version (whether the feature is native in the new version, it's deprecated, or it didn't make any sense in the first place)
