### ISSUE TITLE
account_global_discount missing reset compute fields

### ISSUE THREAD

**Issue by anajuaristi** [OCA/account-invoicing#878]
Case of use:
Create an invoice from sale order including global discount.
Erase the global discount directly on invoice --> invoice_global_discount_ids is correctly emptied but amount_global_discount and amount_untaxed_before_global_discounts are not being recomputed or set to zero, so the global discount amount is staying on invoice causing incorrect amount.

Proposed solution, (I don't know if it's valid or it could be a better one since i'm not expert on this module, nor in programming questions):
Line 133 on https://github.com/OCA/account-invoicing/blob/12.0/account_global_discount/models/account_invoice.py

Modify:
```python
def _compute_amount_one(self):
  if not self.invoice_global_discount_ids:
    return
```

By:
```python
def _compute_amount_one(self):
   if not self.invoice_global_discount_ids:
      self.amount_total_signed = 0
      self.amount_untaxed_signed = 0
   return
```

Please tell us if you would accept the fix and if you want us to upload the PR.
Thank you!
Ana

**Comment by pedrobaeza** [comment]
In v12, if the compute is executed, all values are reset to their default value (0.0 for float/monetary), so I don't think that code will solve your issue.

**Comment by anajuaristi** [comment]
But, it seems that in this case compute is not being executed since the amount values remain with old values. They are never recomputed or reseted to their default value.
I was proposing a way to force this compute. Could it work this way?

**Comment by pedrobaeza** [comment]
You can try in a real installation, but as said, I don't think that solves the problem. Is the problem reproducible in OCA runbot?

**Comment by anajuaristi** [comment]
I was trying to test in OCA runbot to confirm but it's giving me the error 504 Gateway Time-out
So, I will try tomorrow. 
Thank you!

**Comment by anajuaristi** [comment]
Yes. It's happening on runbot
http://3472584-12-0-ea693a.runbot3.odoo-community.org/web#id=10&action=289&active_id=2&model=account.invoice&view_type=form&menu_id=232


This is with 10% global discount, on invoice
Untaxed Amount Before Disc. | $ 41,175.05
-- | --
Global Discounts | $ -4,117.50
Untaxed Amount | $ 37,057.55
Tax | $ 5,558.63
Total | $ 42,616.18

This is after erasing the global discount on invoice
Untaxed Amount	$ 37,057.55
Tax	$ 6,176.26
Total	$ 43,233.81

We have seen in V13, both fields are reseted like in
```
def _compute_amount_one(self):
   if not self.invoice_global_discount_ids:
      self.amount_total_signed = 0
      self.amount_untaxed_signed = 0
   return
```
But the fix is not present on V12. Do you want us to make a PR?

**Comment by pedrobaeza** [comment]
OK, go ahead, but I still think that is not going to solve the problem.
