### ISSUE TITLE
stock_picking_invoicing is not useful anymore

### ISSUE THREAD

**Issue by clonedagain** [OCA/account-invoicing#89]
`stock_picking_invoicing` lets us change the invoice state on pickings, but the standard now lets us do that without a module since https://github.com/odoo/odoo/commit/cdce2e22837e6beafb3f2d8584f8c125bdaba596 .

**Comment by clonedagain** [comment]
@eLBati @lepistone @tafaRU did I miss something?

**Comment by eLBati** [comment]
@clonedagain  I think we missed that change, actually.
Thanks for pointing it out

I just tested the functionality you indicate and I see 2 limitations:
- It's possible to invoice several times the same picking
- Invoiced partner is always the same as the picking's one: the invoicing wizard does not retrieve the 'to be invoiced' partner (by the way, see https://github.com/OCA/account-invoicing/pull/88)

**Comment by clonedagain** [comment]
Indeed.
I think those 2 problems ought to be fixed upstream directly.

**Comment by flotho** [comment]
Hi,

I supposed we are talking about the v8? In v9 it's no more possible to invoice picking

**Comment by pedrobaeza** [comment]
We are talking about v8, and I agree that this module is not needed anymore.

**Comment by flotho** [comment]
So what should be the new name of my module in v9? Won't it be some conflicts if you delete it from v8 and still existing in v9?

**Comment by pedrobaeza** [comment]
I don't think so. There's no problem in putting the same name across versions although there's one without use.

**Comment by pedrobaeza** [comment]
I have removed the module from branches.
