### ISSUE TITLE
[14.0] account_billing test failing

### ISSUE THREAD

**Issue by clementmbr** [OCA/account-invoicing#898]
Hi,

I just made a new PR #897  today to migrate **sale_timesheet_invoice_description** and my Travis is red because of a test failing in **account_billing** :
https://travis-ci.com/github/OCA/account-invoicing/jobs/493419132#L1411

Looks like this test has nothing to do with **sale_timesheet_invoice_description** as it just creates a billing object and my module only changes the invoice line's description under some condition.

Any idea why this test is failing @komsan-S ?

Thanks !

**Comment by kittiu** [comment]
Fixed https://github.com/OCA/account-invoicing/pull/911
