### ISSUE TITLE
[12.0] Order line billed quantity not updated

### ISSUE THREAD

**Issue by jypsmh** [OCA/account-invoicing#904]
After merging 2 invoices, billed quantity on order is not updated.

**Comment by sergiocorato** [comment]
Billed quantities are updated on invoice creation, invoice merge is not involved AFAIK.

**Comment by jypsmh** [comment]
not agree in v12
2 orders, with 2 deliveries, 2 draft invoices : ok, we see billing quantity on purchase orders
account invoice merge of the 2 draft invoices
a new draft invoice is generated ok, and the 2 original draft invoices are cancelled
but the cancel of original invoices remove the billing quantity on purchase orders
