### ISSUE TITLE
[12.0] account_invoice_triple_discount Discount 2 and 3 missing in invoice view/report but are calculated correctly

### ISSUE THREAD

**Issue by antonionardella** [OCA/account-invoicing#914]
Hello,

a SO with three discounts as shown here:
![image](https://user-images.githubusercontent.com/7383572/114708703-fbe25200-9d2b-11eb-8988-6f464a3003c4.png)

does not keep the discount 2 and 3 in the invoice view and report
![image](https://user-images.githubusercontent.com/7383572/114708779-1ae0e400-9d2c-11eb-918e-e3f6adab44fb.png)
 
Although the discounts are correctly calculated

**Comment by legalsylvain** [comment]
Hi. This module hide the values, if you're are not member of the group ``base.group_no_one``.

https://github.com/OCA/account-invoicing/blob/12.0/account_invoice_triple_discount/views/account_invoice_view.xml#L11

I think that is not good design, (and not consistent with the rest of Odoo).

Could you make a PR, removing the groups fields ? 

thanks !
