### ISSUE TITLE
[12] [account_invoice_merge] not getting lot /serials if using module [account_invoice_production_lot]

### ISSUE THREAD

**Issue by JordiADARIA** [OCA/account-invoicing#917]
if use [account_invoice_production_lot],  account_invoice_merge is not getting lot/serial numbers on printed merged invoice.

Make sense to add it (if exist field on origin invoice line)

it's possible to add it, if the field "prod_lot_ids" exists on origin invoice line?

i guess it should be added here (if exist):

def _get_first_invoice_fields(self, invoice):
        return {
            'origin': '%s' % (invoice.origin or '',),
            'partner_id': invoice.partner_id.id,
            'journal_id': invoice.journal_id.id,
            'user_id': invoice.user_id.id,
            'currency_id': invoice.currency_id.id,
            'company_id': invoice.company_id.id,
            'type': invoice.type,
            'account_id': invoice.account_id.id,
            'state': 'draft',
            'reference': '%s' % (invoice.reference or '',),
            'name': '%s' % (invoice.name or '',),
            'fiscal_position_id': invoice.fiscal_position_id.id,
            'payment_term_id': invoice.payment_term_id.id,
            'invoice_line_ids': {},
            'partner_bank_id': invoice.partner_bank_id.id,
            **xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,**
        }

**Comment by legalsylvain** [comment]
Hi @JordiADARIA. I think you could implement a fix similar to this one : https://github.com/OCA/account-invoicing/pull/918

could you review the PR ? and make another PR, once this one validated ? 

thanks !

**Comment by JordiADARIA** [comment]
oh, @legalsylvain , ill try to use the approach that you uses with that PR, it could be enough (before i need to check if that field exist, if i want to avoid errors due to field nonexistence) ... if its ok ill try to make a PR

thanks a lot for your suggestion!
