### ISSUE TITLE
[13.0] sale_order_invoicing_grouping_criteria

### ISSUE THREAD

**Issue by acsonefho** [OCA/account-invoicing#920]
I think there is a issue with the module `sale_order_invoicing_grouping_criteria` (v`13.0`).

The idea is to add some values/keys during creation of invoices based on sale orders to group them if necessary.

If I correctly understood the Odoo sale addon, it generated values (`dict`) to create future invoices based on current sale orders.
Then these values are grouped together depending on group keys (keys added by this module are added here, that sounds great).

But to define those keys, we have to use `sale.order`'s fields. I think that's the issue. Because Odoo use the generated `invoice_vals` (so a `dict`) and not values of the `sale.order` record.
https://github.com/odoo/odoo/blob/13.0/addons/sale/models/sale.py#L664

**How to reproduce:**
- Create 2 sale orders with same `partner_id`, `company_id` and `currency_id` (base fields used by Odoo to group them);
- Then into the module configuration, define a criteria with the `id` field (as the ID is unique, it shouldn't group these 2 SO; The goal is to have 2 invoices);
- Use this configuration on the partner (or global configuration, as you want);
- Select these 2 SO and use the "more" menu to generate an invoice based on them.
We expect 2 invoices as the `id` is unique. But we have only 1 single invoice grouping 2 SO :boom: .

If you put a break point, that's confirm the issue: criteria are `[1, 112069, 1, None]` who's match with (`company_id`, `partner_id`, `currency_id`, `id`).
As `id` is not into the `dict` generated by `order._prepare_invoice()`, the value is `None`.

**How to fix:**
I think we can let the user specify some string keys (separated by `,`) instead of restrict him to use `sale.order`'s fields who are not usable at all.

**Comment by acsonefho** [comment]
@pedrobaeza can you take a look please? I think you already work on this module.
Thanks in advance!

**Comment by pedrobaeza** [comment]
The grouping criteria uses `sale.order` values:

https://github.com/OCA/account-invoicing/blob/afce74cdfe52a65f920a7fc4195554d47b3ce477/sale_order_invoicing_grouping_criteria/models/sale_order.py#L23

so there's something weird in your case, but it should perfectly worked.

**Comment by acsonefho** [comment]
> The grouping criteria uses `sale.order` values:
> 
> https://github.com/OCA/account-invoicing/blob/afce74cdfe52a65f920a7fc4195554d47b3ce477/sale_order_invoicing_grouping_criteria/models/sale_order.py#L23
> 
> so there's something weird in your case, but it should perfectly worked.

You're right! Sorry I was on a previous version of this module and with the update it works perfectly!

Thank you!
