### ISSUE TITLE
[13.0] account_invoice_refund_line_selection: Not working as expected

### ISSUE THREAD

**Issue by samako41** [OCA/account-invoicing#970]
Hello,

Please be aware that version 13 of Account invoice refund line module that is on odoo app store is not functioning as it ought to.

When you select invoice lines, all the lines are added to the credit note instead and they will all be processed which is not right.

We will appreciate if you can help us do amendment to this as we consider it to be a useful module to us.

Thank you

**Comment by AaronHForgeFlow** [comment]
Are you able to reproduce the same on runbot: http://3493292-13-0-26be19.runbot1-3.odoo-community.org/web/login?db=3493292-13-0-26be19-all&login=admin&redirect=/web?debug=1 ?

**Comment by samako41** [comment]
I can see that what was built was to refund specific lines before register
payment. What i was looking for is to refund specific lines even after
payment. I thought it was meant to do this.

Thanks & Regards
.

**Comment by AaronHForgeFlow** [comment]
In that case I think you have to unreconcile the payment first, then you can refund the specific lines.
