### ISSUE TITLE
sale_timesheet_invoice_description for Odoo 14

### ISSUE THREAD

**Issue by dstainhauser** [OCA/account-invoicing#980]
Hi

I'm a happy user of sale_timesheet_invoice_description, currently with Odoo 12. We are now migrating to Odoo 14, but the module is not yet ported to Odoo 14. I tried to install it, but it seems there is a change with sequence.

```
File "/opt/odoo/14.0/odoo/addons/sale_timesheet/wizard/sale_make_invoice_advance.py", line 43, in create_invoices
    sale_orders._create_invoices(final=self.deduct_down_payments, start_date=self.date_start_invoice_timesheet, end_date=self.date_end_invoice_timesheet)
  File "/opt/odoo/14.0/odoo/addons/sale_timesheet/models/sale_order.py", line 73, in _create_invoices
    moves = super(SaleOrder, self)._create_invoices(grouped, final)
  File "/opt/odoo/14.0/odoo/addons/sale/models/sale.py", line 700, in _create_invoices
    (0, 0, line._prepare_invoice_line(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _prepare_invoice_line() got an unexpected keyword argument 'sequence'


```
What are the plans for Odoo 14? I would really appreciate using this module again, as I don't see any other alternative.

Thanks for your valuable work

Daniel

**Comment by bosd** [comment]
I'm using it in production without any major problems.
There seems to be a small bug.
After the installation you need to set the Invoiceline description on already exsisting projects.
Otherwise it will throw an server error.

(Though I already opened an issue about this, but cannot find it)

**Comment by bosd** [comment]
found it here: https://github.com/OCA/account-invoicing/pull/897#pullrequestreview-861434986
@dstainhauser  Is this similar to your issue?

**Comment by pedrobaeza** [comment]
Already migrated
